# -*- coding: utf-8 -*-
"""freq

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/sasha110110/cb39fb3ef36a9c2127d715e5fdbb4696/freq.ipynb
"""

#списки

text="языки программирования, Обязанности :обеспечение прибыльного функционирования спортивного клуба,\
выполнение бюджета, выполнение установленных коммерческих планов, язык разметки\
формирование и удержание команды,   автоматизация API, автоматизация API,\
экономической деятельностью клуба,   обеспечение высокого уровня обслуживания\
клиентов,   составление отчетов различного уровня.  "

text2="языки программирования, Обязанности :обеспечение прибыльного функционирования спортивного клуба,\
выполнение бюджета, выполнение установленных коммерческих планов,\
формирование и удержание команды,   автоматизация API, Автоматизация Bash, язык запросов, эссе"

tools=["языки программирования", "язык разметки", "язык запросов", "эссе"]

resp=["автоматизация API", "Автоматизация Bash"]

### easy variant
from collections import defaultdict

def how_often(vacancies):
  
  d=defaultdict(list)
  for text in vacancies:
    for keys in tools:
        for keys2 in resp:
          if keys in text:
            if keys2 in text:
              try:
                d[keys].append(keys2)
               #list_of_items.append(key, key2) 
              except Exception:
                continue
             
            
  return d

d=how_often([text, text2])

d

def count_result(d):
  
  for k, v in d.items():
    counts = dict()
    for item in v:
      counts[item] = counts.get(item, 0) + 1
    yield [k, counts]

itog=list(count_result(d))

itog

itog_itog=[]
for item in itog:
  temp=[]
  for k, v in item[1].items():
    result=[k, v, v/sum(item[1].values())]
    temp.append(result)
  itog_itog.append([item[0], temp])

itog_itog

import pandas as pd

itog_pd=pd.DataFrame(itog_itog) #сделать нормальную



"""другой вариант с регулярными выражениями, чтобы не пропустить падежи, 
сделать: выцепить текст из результата, group() не работает с кириллицей
"""

def make_regular_patterns(tools):
  patterns=[]
  for keys in tools:
    if " " in keys:
      keys_split=keys.split()
      pattern=keys_split[0][0:-3]+".*?"+keys_split[-1]
      patterns.append(pattern)
    else:
      patterns.append(keys)
  return patterns

patte=make_regular_patterns(tools)

patte2=make_regular_patterns(resp)

from collections import defaultdict

d = defaultdict(list)

def how_often(text):
    for keys in patte:
        for keys2 in patte2:
          k=re.search(keys, text) #re.I|re.U).group()
          v=re.findall(keys2, text)
          if k:
            if v:
              d[k].append(v)
          
                #if keys2 in text:
            #d[re.search(keys, text).group(0)].append(re.findall(keys2, text))
    return d